version: '3'

networks:
  dnv-net:
    name: dnv-net

services:
  db-service:
    image: catapi-db-service
    container_name: catapi-db-service
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: 3307 
    expose:
      - "3307"
    ports:
      - "3307:3307"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - dnv-net
  api-service:
    image: catapi-api-service
    container_name: catapi-api-service
    build: ./api
    ports:
      - 1994:1994
    depends_on:
      - db-service
    networks:
      - dnv-net
  dash-service:
    image: catapi-dash-service
    container_name: catapi-dash-service
    build: ./app
    networks:
      - dnv-net
  shinyproxy:
    image: catapi-shinyproxy-service
    container_name: catapi-shinyproxy-service
    restart: on-failure
    build: ./shinyproxy
    networks:
      - dnv-net
    ports:
      - 8080:8080
    depends_on:
      - api-service
      - db-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml